<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>secure.prop.util</groupId>
  <artifactId>secure-properties-gui-tool</artifactId>
  <version>0.0.2-SNAPSHOT</version>
  <organization>
    <name>254d</name>
    <url>https://github.com/254d/secure-properties-gui-tool</url>
  </organization>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <maven.compiler.release>17</maven.compiler.release>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
      <version>17</version>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-fxml</artifactId>
      <version>17</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
      <version>1.18.46</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.6.2</version>
    </dependency>
    <dependency>
      <groupId>com.mulesoft.tools</groupId>
      <artifactId>secure-properties-tool</artifactId>
      <version>j17</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/lib/secure-properties-tool-j17.jar</systemPath>
    </dependency>
  </dependencies>
  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
          <release>${maven.compiler.release}</release>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.46</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <!-- Source:
      https://mvnrepository.com/artifact/io.github.download-maven-plugin/download-maven-plugin -->
      <plugin>
        <groupId>io.github.download-maven-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>2.1.0</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>
                https://docs.mulesoft.com/mule-runtime/latest/_attachments/secure-properties-tool-j17.jar</url>
              <outputDirectory>${project.basedir}/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Source:
      https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-dependency-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <phase>prepare-package</phase>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/classes</outputDirectory>
              <includeArtifactIds>secure-properties-tool</includeArtifactIds>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Source: https://mvnrepository.com/artifact/org.openjfx/javafx-maven-plugin -->
      <!-- mvn clean javafx:run -->
      <plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>0.0.8</version>
        <configuration>
          <mainClass>secure.prop.utils.SecurePropertiesGui</mainClass>
        </configuration>
      </plugin>
      <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-assembly-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <appendAssemblyId>false</appendAssemblyId>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>secure.prop.utils.SecurePropertiesGuiEntryPoint</mainClass>
            </manifest>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.akathist.maven.plugins.launch4j</groupId>
        <artifactId>launch4j-maven-plugin</artifactId>
        <version>2.7.0</version>
        <executions>
          <execution>
            <id>l4j-clui</id>
            <phase>package</phase>
            <goals>
              <goal>launch4j</goal>
            </goals>
            <configuration>
              <headerType>gui</headerType>
              <outfile>target/${project.artifactId}.exe</outfile>
              <jar>target/${project.artifactId}.jar</jar>
              <errTitle>Secure Properties GUI Tool</errTitle>
              <stayAlive>false</stayAlive>
              <jre>
                <minVersion>17</minVersion>
              </jre>
              <versionInfo>
                <fileDescription>Secure Properties GUI Tool</fileDescription>
                <copyright>254d</copyright>
                <productName>Secure Properties GUI Tool</productName>
              </versionInfo>
              <icon>src/main/resources/icon/main.ico</icon>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>